---
  web:
    build: .
    command: bash -c "/usr/sbin/httpd && ping www.baidu.com" 
    restart: always
    hostname: 'www.example.com'
    ports:
      - '8080:80'
    volumes:
      - ./index.html:/var/www/html/index.html
  
